name: Baseline Check Action

on:
  push:
    branches: [ main ]

jobs:
  baseline-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run baseline check
        run: node index.js

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: baseline-report
          path: data/baseline-report.json

      - name: Commit report to repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/baseline-report.json
          git commit -m "Update baseline report [skip ci]" || echo "No changes to commit"
          git push


